<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Validation\Support\I18n;

use Simtabi\Laranail\Validation\Contracts\I18n\CountryDataset;

/**
 * The bundled ISO 3166-1 registry — 250 alpha-2 codes (the 249 assigned plus
 * the user-assigned XK, which real address data requires) and the 249
 * assigned alpha-3 codes.
 *
 * Generated by `tools/build-datasets.php` from a cross-checked snapshot; a
 * suite test regenerates and compares, so the data cannot drift from its
 * committed source unnoticed. Lazy per list: an application that never
 * validates a country pays nothing.
 */
final class BundledCountryDataset implements CountryDataset
{
    /** @var array<string, true>|null */
    private ?array $alpha2 = null;

    /** @var array<string, true>|null */
    private ?array $alpha3 = null;

    public function isAlpha2(string $code): bool
    {
        $this->alpha2 ??= CodeFile::load(__DIR__ . '/../../../resources/data/iso-3166-alpha2.txt');

        return isset($this->alpha2[$code]);
    }

    public function isAlpha3(string $code): bool
    {
        $this->alpha3 ??= CodeFile::load(__DIR__ . '/../../../resources/data/iso-3166-alpha3.txt');

        return isset($this->alpha3[$code]);
    }
}
