name: Rector

on:
  push:
    paths:
      - '**.php'
      - 'rector.php'
      - '.github/workflows/rector.yml'
  pull_request:
    paths:
      - '**.php'
      - 'rector.php'
      - '.github/workflows/rector.yml'

permissions:
  contents: write

jobs:
  rector:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Cache Rector results
        uses: actions/cache@v6
        with:
          path: .cache/rector/
          key: rector-cache-${{ hashFiles('rector.php') }}
          restore-keys: rector-cache-

      - name: Run Rector
        run: |
          mkdir -p .cache/rector .cache/rectorContainer
          vendor/bin/rector process --no-diffs

      - name: Pull latest changes
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          git stash
          git pull --rebase origin "$BRANCH"
          git stash pop || true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'chore: rector'
