name: Rector

on:
  pull_request:
    paths:
      - '**.php'
      - 'rector.php'
      - '.github/workflows/rector.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  rector:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Cache Rector results
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .cache/rector/
          key: rector-cache-${{ hashFiles('rector.php') }}
          restore-keys: rector-cache-

      - name: Run Rector
        run: |
          mkdir -p .cache/rector .cache/rectorContainer
          vendor/bin/rector process --no-diffs

      - name: Pull latest changes
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          git stash
          git pull --rebase origin "$BRANCH"
          git stash pop || true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: 'chore: rector'
